return {
	status = {
		working = "",
		active = "",
		active_ts = "",
		check = "✓",
		close = "󰅖",
		ellipsis = "…",
		selected = "❯",
	},
	dap = {
		breakpoint = "",
		breakpoint_condition = "",
		breakpoint_rejected = "",
		log_point = "󰛿",
		stopped = "󰁕",
	},
	diagnostics = {
		default = "󰒡",
		error = "",
		hint = "󰌵",
		info = "󰋼",
		warn = "",
		warning = "",
	},
	files = {
		default = "󰈙",
		new = "",
		modified = "",
		read_only = "",
		word = "󰈭",
	},
	folds = {
		closed = "",
		open = "",
		separator = " ",
	},
	folders = {
		closed = "",
		empty = "",
		empty_open = "",
		open = "",
	},
	git = {
		repo = "󰊢",
		github = " ",
		branch = "",
		add = "",
		modified = "",
		removed = "",
		rename = "➜",
		renamed = "➜",
		conflict = "",
		ignored = "◌",
		staged = "✓",
		unstaged = "✗",
		untracked = "★",
		sign = "▎",
		sign_line = "",
		diff = "",
	},
	spinner = {
		short = { "", "󰀚", "" },
		dots = { "⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏" },
	},
	misc = {
		bookmarks = "",
		list = "",
		paste = "󰅌",
		refresh = "",
		search = "",
		sort = "󰒺",
		spellcheck = "󰓆",
		tab = "󰓩",
		window = "",
	},
	tools = {
		debugger = "",
		environment = "",
		lsp = "",
		macro_recording = "",
		package = "󰏖",
		session = "󱂬",
		terminal = "",
		open_code = "",
		robot = "󰚩",
		harpoon = "󱡀",
		tests = "󰗇",
		watch = "",
	},
}
